
                    <article>
                        <div class="search">
                            <form action="search.html" class="solire-js-search-form" method="get" style="display:inline-block; font-size:0;">
                                <input type="text" name="term" class="solire-js-search input-shadow degrade_grisclair_invert form-controle form-oblig form-mix" placeholder="<?php echo $this->_("recherche..."); ?>" value="<?php echo $this->search; ?>" />
                                <input type="submit" class="submit menu-submit" value="" style="box-shadow:0px; line-height:2;"/>
                            </form>
                        </div>
                    </article>
