<?php echo'<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.google.com/schemas/sitemap/0.84">'; ?>
<?php foreach ($this->pages as $page) { ?>
	<url>
		<loc><?php echo $this->url . $page['path'] ?></loc>
		<lastmod><?php echo $page['lastmod']; ?></lastmod>
		<priority><?php echo $page['importance'] > 9 ? 1 : '0.' . $page['importance']; ?></priority>
	</url>
<?php } ?>
</urlset>
