<div class="modal-body">

    <form id="mercury_html_editor" class="form-horizontal" style="width: 600px;">  
                    <textarea class="mercury-display-pane-container" rows="5" style="width:100%"></textarea>  
    </form>
</div>
<div class="modal-footer">    
    <input class="submit btn btn-small btn-primary" name="commit" onclick="$('#mercury_html_editor').submit()" type="submit" value="Sauvegarder et remplacer"/>
</div>
