<div class="modal-body" id="mercury_media_modal">

    <form id="mercury_media" class="form-horizontal" style="width: 600px;">  
                    <div class="select input optional control-group" id="media_image_alignment_input"> 
                        <label style="margin-right: 6px;" for="media_image_list" class="control-label">Liste d'images</label>              
                        <select name="" class="media_image_list" id="media_image_list"></select> 
                    </div>  
                    <div class="select input optional control-group" id="media_image_alignment_input"> 
                        <label style="margin-right: 6px;" for="media_image_list" class="control-label">&nbsp;</label>  
                        <button id="pickfiles" class="btn btn-small btn-success" href="#" style="position: relative; z-index: 0;"><i class="icon-folder-open"></i> Ajouter un fichier</button>
                    </div>  

                    <div id="media_image_url_input" class="string input optional stringish  control-group">            
                        <label style="margin-right: 6px;" class="control-label" for="media_image_url"><input name="media_type" type="hidden" value="image_url" checked="checked"/>URL</label>            
                        <div class="input-append">
                            <input class="selectable" id="media_image_url" name="media[image_url]" type="text"/> 
                            <a title="Prévisualisation" target="_blank" href="" class="btn previsu"><i class="icon-camera"></i></a>
                            <a title="Recadrer" href="#" class="btn crop"><i class="icon-fullscreen"></i></a>    
                        </div>
                    </div>     
    </form>
</div>
<div class="modal-footer">    
    <input class="submit btn btn-small btn-primary" name="commit" onclick="$('#mercury_media').submit()" type="submit" value="Insérer le visuel"/>
</div>
