<script type="text/javascript">
    var head = document.getElementsByTagName("head")[0];
    function loadCss(src) {
        var link = document.createElement('link');
        link.href = src;
        link.media = 'screen';
        link.rel = 'stylesheet';
        link.type = 'text/css';
        head.appendChild(link);
    }
    function loadScript(src, callback) {
        var script = document.createElement('script');
        script.src = src;
        script.type = 'text/javascript';
        script.charset = 'utf-8';
        head.appendChild(script);
        script.onload = function() {
            document.body.style.visibility = 'visible';
            document.body.style.display = 'block';
            if (callback && typeof(callback) === "function") {
                callback();
            }
        };
    }
</script>

<?php
    if (isset($this->page)) {
?>


    <?php $this->add('../../back/view/template/cropdialog'); ?>
    <script src='app/back/js/mercury/mercury_loader.js?src=<?php echo $this->url; ?>app/back/js/mercury&pack=bundled&visible=false'></script>
    <!--<script src="app/back/js/jquery/jquery-ui-1.8.23.custom.min.js" type="text/javascript"></script>-->


    <script type="text/javascript">

        function upload() {
            /** UPLOAD FICHIER*/
            var uploader, basehref

            basehref = $('base').attr('href');

            uploader = new plupload.Uploader({
                runtimes: 'gears,html5,silverlight,flash,html4',
                browse_button: 'pickfiles',
                max_file_size: '1000mb',
                chunk_size: '2mb',
                url: basehref + 'back/media/upload.html?id_gab_page=<?php echo $this->page->getMeta("id") ?>',
                flash_swf_url: basehref + 'js/admin/plupload/plupload.flash.swf',
                silverlight_xap_url: basehref + 'js/admin/plupload/plupload.silverlight.xap',
                filters: [
                    {
                        title: "Image files",
                        extensions: "jpg,jpeg,gif,png"
                    }
                ],
                drop_element: 'colright',
                unique_names: false,
                multiple_queues: true
            });

            uploader.bind('Init', function(up, params) {
                $('#currentruntime').text("Current runtime: " + params.runtime);
            });

            var uploaderInited = false;

            var uploaderInit = function() {
                if (!uploaderInited) {
                    uploaderInited = true;

                    uploader.init();

                    uploader.bind('FilesAdded', function(up, files) {
                        $.each(files, function(i, file) {
                            var tr, td;
                            if (!file.error) {
                            }
                            else
                                uploader.splice(i, 1);
                        });

                        $.each(files, function(i, file) {
                        });

                        up.refresh();
                        up.start();
                    });

                    uploader.bind('UploadProgress', function(up, file) {
                        //                    $('.progressbar', file.tr).progressbar("value", file.percent);
                    });

                    uploader.bind('Error', function(up, err) {
                        err.file.error = true;
                        up.refresh();
                    });

                    uploader.bind('FileUploaded', function(up, file, info) {

                        uploader.splice(0, 1);
                        if (uploader.files.length == 0) {
                            loadSelectImages($("#mercury_media:first")[0])
                        }
                    });
                }
                else {
                    uploader.refresh();
                }
            };

            $('#pickfiles').live('click', function(e) {
                e.preventDefault();
            });

            uploaderInit();

            /** FINUPLOAD FICHIER*/
        }

        function loadSelectImages(element) {


            $.get("back/media/autocomplete.html?id_gab_page=<?php echo $this->page->getMeta("id") ?>", function(data) {
                $selectImage = $(element).find(".media_image_list")
                $selectImage.empty().append('<option></option>');
                $inputImage = $selectImage.parents("form:first").find("#media_image_url")
                $.each(data, function(id, item) {
                    var beforeLastSlash = item.path.lastIndexOf("/", item.path.lastIndexOf("/") - 1) + 1
                    var selected = $inputImage.val() == item.path.substr(beforeLastSlash) ? 'selected="selected"' : '';
                    $selectImage.append('<option ' + selected + ' value="' + item.path.substr(beforeLastSlash) + '">' + item.label + ' (' + item.size + ')</option>');
                })
                $selectImage.bind("change", function() {
                    var value = $(this).val()
                    $selectImage.parents("form:first").find(".previsu").attr("href", value)
                    $selectImage.parents("form:first").find("#media_image_url").val(value)
                })

            }, "json")
        }

        $(function() {
            loadScript("app/back/js/smallipop/jquery.smallipop.js", function() {
                $('[data-smallipop=true]').smallipop({
                    preferredPosition: 'right',
                    theme: 'black',
                    popupOffset: 0,
//                    triggerOnClick: true,
                    hideOnPopupClick: false,
                    onBeforeShow: function() {
                        if ($("[data-mercury]").length == 0) {
                            return false;
                        }
                    },
                    onBeforeHide: function(trigger) {
                        if ($(trigger).find("textarea").length > 0) {
                            if ($(trigger).find("textarea")[0] === $("*:focus")[0]) {
                                return false;
                            }
                        } else {
                            if ($(trigger)[0] === $("*:focus")[0]) {
                                return false;
                            }
                        }
                    }
                });
            })
            loadCss("app/back/css/smallipop/jquery.smallipop.css")



            $(document).bind('DOMNodeInserted', function(e) {
                var element = e.target;
                if ($(element).attr("id") == "mercury_media_modal" && $(element).find(".media_image_list").length == 1) {
                    loadSelectImages(element)
                    loadScript("app/back/js/plupload/plupload.full.min.js", function() {
                        upload()
                    })


                }

                if ($(element).hasClass("mercury-editable-toolbar")) {

                    $(".mercury-save-button, .mercury-preview-button").addClass('btn btn-success btn-small').removeClass("mercury-button")
                    $(".mercury-save-button").html('<i class="icon-ok"></i> Valider')
                    $(".mercury-preview-button").html('<i class="icon-edit"></i> Masquer les zones éditables').css({"margin-right" : "10px"})
                }

                if ($(element).attr("id") == "mercury_iframe") {

                    $(element).ready(function() {
                        $("#mercury_iframe").after('<div id="back-toolbar-container"></div>')

                        loadScript("app/back/js/jquery/jquery-ui-1.8.23.custom.min.js")
                        loadScript("app/back/js/jquery/jcrop/jquery.Jcrop.min.js")
                        loadScript("app/back/js/jquery/ui.spinner.min.js")
                        loadScript("app/back/js/main.js?admin")
                        loadScript("app/back/js/jquery/sticky.js?admin")

                        loadCss("app/back/css/jcrop/jquery.Jcrop.min.css")
                        loadCss("app/back/css/jquery-ui-1.8.7.custom.css")
                        loadCss("app/back/css/bootstrap/bootstrap-responsive.min.css")
                        loadCss("app/back/css/bootstrap/bootstrap.min.css")
                        loadCss("app/back/css/ui.spinner.css")
                        loadCss("app/back/css/crop.css")
                        loadCss("app/back/css/sticky.css")

                        $("#back-toolbar-container").css({"width": "100%", "z-index": "20000", "position": "fixed"}).load("middleoffice/toolbarback.html", {currentUrl : "<?php echo $this->currentUrl; ?>", id_gab_page : <?php echo $this->page->getMeta("id") ?>, id_api : <?php echo $this->page->getMeta("id_api") ?>}, function() {
                            cloneModalCrop.appendTo("body")
                            loadScript("app/back/js/bootstrap/bootstrap.min.js?admin", function(){
                                loadScript("app/back/js/crop_front.js");
                            });
                            $(".mode_normal").click(function(e) {
                                if($(".visible-lang input").length != 0 && !$(".visible-lang input").is(":checked")) {
                                    e.preventDefault()
                                    var heading = 'Passer en mode normal (pages visibles)';
                                    var question = 'Attention, cette page n\'est pas visible, vous allez être redirigé vers la page d\'accueil, malgré cela êtes-vous sûr de vouloir continuer ? ';
                                    var cancelButtonTxt = 'Annuler';
                                    var okButtonTxt = 'Continuer';
                                    var href = $(this).attr("href");
                                    var callback = function() {
                                        document.location.href = $("base").attr("href");
                                    }

                                    myModal.confirm(heading, question, cancelButtonTxt, okButtonTxt, callback, 12010);
                                }
                            })
                        })
                        //                  $("<iframe>", {
                        //                seamless: 'true',
                        //                frameborder: '0'}).css("width", "100%").attr("src", "middleoffice/toolbarback.html?id_gab_page=" + <?php echo $this->page->getMeta("id") ?>).prependTo(document.body)
                        $(element).css("top", "40px");
                    })
                }

                if ($(element).attr("id") == "mercury_link" && $(element).find(".media_link_list").length == 1) {
                    $.get("sitemap.xml?json=1&visible=0&term=", function(data) {
                        $selectLink = $(element).find(".media_link_list")
                        $selectLink.empty().append('<option></option>');
                        $.each(data, function(id, item) {
                            $selectLink.append('<option value="' + item.path + '">' + item.title + '</option>');
                        })

                        $selectLink.bind("change", function() {
                            var value = $(this).val()
                            $selectLink.parents("form:first").find("#link_external_url").val(value)
                        })

                    }, "json")

                }


            });
        });

        window.mercuryPackages = {
            development: {javascripts: 'mercury.js', stylesheets: 'mercury.css'},
            bundled: {javascripts: 'mercury.js,mercury_dialogs.js', stylesheets: '../../css/mercury/mercury.css'}
        };



        function toggleMercury() {
            if (typeof(Mercury) == 'undefined') {
                alert("Sorry, but Mercury Editor isn't supported by your current browser.\n\nBrowsers that support the required HTML5 spec:\n\n  Chrome 10+\n  Firefox 4+\n  Safari 5+\n  Opera 11.64+\n  Mobile Safari (iOS 5+)");
            } else {
                Mercury.trigger('toggle:interface');
                Mercury.config.uploading = {
                    enabled: true,
                    allowedMimeTypes: ['image/jpeg', 'image/gif', 'image/png'],
                    maxFileSize: 1235242880,
                    inputName: 'file',
                    url: '<?php echo $this->url; ?>back/media/upload.html?id_gab_page=<?php echo $this->page->getMeta("id") ?>',
                                    handler: false
                                };
                                Mercury.PageEditor.prototype.save = function() {
                                    var data = this.serialize();
                                    data.id_gab_page = {value: <?php echo $this->page->getMeta("id") ?>};
                                    data.id_version = {value: <?php echo $this->page->getMeta("id_version") ?>};
                                    data.id_gabarit = {value: <?php echo $this->page->getMeta("id_gabarit") ?>};
                                    data.id_api = {value: <?php echo $this->page->getMeta("id_api") ?>};
                                    var lightview = Mercury.lightview(null, {title: 'Enregistrement en cours, veuillez patientez ...', closeButton: true});
                                    setTimeout(function() {
                                        $.post('<?php echo $this->url; ?>back/page/save.html?edit-front=1', {content: top.JSON.stringify(data, null)}, function() {
                                            lightview.loadContent('<div style="width:500px">La page a été enregistrée avec succès</div>', {title: 'Succès de l\'enregistrement de la page', closeButton: true});
                                            javascript:toggleMercury()
                                        });
                                    }, 500);
                                }

                                //        loadScript("back/js/jquery/jquery-1.8.0.min.js")

                            }
                        }
    </script>



    <script>
        var cloneModalCrop = $('#modalCrop').clone()
        $('#modalCrop').remove()
        jQuery(parent).trigger('initialize:frame');

    </script>



<?php
    } else {
?>
    <script type="text/javascript">
        $(function() {
            loadScript("app/back/js/bootstrap/bootstrap.min.js?admin")
            loadScript("app/back/js/main.js?admin")

            loadCss("app/back/css/bootstrap/bootstrap-responsive.min.css")
            loadCss("app/back/css/bootstrap/bootstrap.min.css")
            $("body").prepend('<div id="back-toolbar-container"></div>')
            $("#back-toolbar-container").css({"width": "100%", "z-index": "20000", "position": "fixed"}).load("middleoffice/toolbarback.html", {currentUrl : "<?php echo $this->currentUrl; ?>"}, function() {

            })
        });
    </script>
<?php
    }
?>
