
    <?php
    foreach ($this->breadCrumbs as $iLink => $link) {
        ?>
        <?php
        if ($iLink == count($this->breadCrumbs) - 1) {
            ?>
            <span><strong><?php echo $link["title"]; ?></strong></span>
            <?php
        } else {
            ?>
            <a href="<?php echo $link["url"]; ?>"><?php echo $link["label"]; ?></a>
            <?php
        }
        ?>

        <?php
    }
    ?>
    
  