<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="<?php echo strtolower(SUF_VERSION); ?>" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <title><?php echo $this->seo->getTitle(); ?></title>
        <meta name="description" content="<?php echo $this->seo->getDescription(); ?>" />
        <meta name="keywords" lang="<?php echo strtolower(SUF_VERSION); ?>" content="<?php echo $this->seo->showKeywords(); ?>" />


        <meta name="language" content="<?php echo strtolower(SUF_VERSION); ?>" />
        <meta name="robots" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />
        <meta name="googlebot" content="<?php echo $this->seo->getIndex(); ?>index, <?php echo $this->seo->getFollow(); ?>follow, all" />

        <meta name="google-site-verification" content="<?php echo $this->mainPage["element_commun"]->getValues("code_google_webmaster_tools"); ?>" />
        <meta name="msvalidate.01" content="<?php echo $this->mainPage["element_commun"]->getValues("code_bing_webmaster_tools"); ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="generator" content="Solire" />
        <!--[if lt IE 9]>
            <script src="<?php echo $this->url; ?>app/front/js/html5.js"></script>
        <![endif]-->
<?php
    if ($this->seo->getAuthor() != "") {
?>
        <link rel="author" href="https://plus.google.com/<?php echo $this->seo->getAuthor(); ?>" title="<?php echo $this->seo->getAuthorName(); ?>" type="text/html">
<?php
    }
?>
        <base href="<?php echo $this->url; ?>" />

<?php
    if ($this->seo->getUrlCanonical() != "") {
?>
        <link rel="canonical" href="<?php echo $this->seo->getUrlCanonical(); ?>"/>
<?php
    }

    echo $this->css->outputAll();
?>
        <script type="text/javascript">window.jQuery || document.write('<script type="text/javascript" src="<?php echo $this->javascript->getPath('front/js/jquery/jquery-1.7.min.js'); ?>"><\/script>')</script>
<?php
    if ($this->utilisateurAdmin->isConnected() && !$this->modePrevisuPage && (isset($_GET['mercury_frame']) || !isset($this->page))
        || !$this->utilisateurAdmin->isConnected()
    ) {
        echo $this->javascript->outputAll();
    }
?>
    </head>

    <body role="document"  itemscope itemtype="http://schema.org/WebPage">
<?php
    if ($this->utilisateurAdmin->isConnected() && !$this->modePrevisuPage && !isset($_GET['mercury_frame'])) {
        $this->add('middleoffice/toolbar');
    }
?>


        <header role="banner">
            <?php $this->add('menu'); ?>
        </header>
        <!-- End header -->

        <div class="ariane" itemprop="breadcrumb"><?php $this->add('breadcrumbs'); ?></div>


        <?php $this->content(); ?>


        <footer>
<?php
    if($this->mainPage["element_commun"]->getValues("publisher") != "") {
?>
        <a target="_blank" rel="publisher" href="https://plus.google.com/<?php echo $this->mainPage["element_commun"]->getValues("publisher"); ?>"><?php echo $this->mainPage["element_commun"]->getValues("publisher_nom"); ?></a>
<?php

    }
?>
        </footer>
        <!-- End footer -->


        <script type="text/javascript">

            <?php echo $this->mainPage["element_commun"]->getValues("code_google_analytics"); ?>

        </script>
    </body>
</html>



